name: Deploy to EKS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPO }}:latest .
        docker tag ${{ secrets.ECR_REPO }}:latest public.ecr.aws/k5u0o7b3/team2-namegen:latest

    - name: Push Docker image to ECR
      run: |
        docker push public.ecr.aws/k5u0o7b3/team2-namegen:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s-manifests/