name: Deploy to EKS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Log in to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t public.ecr.aws/k5u0o7b3/team2-namegen:latest .
    
    - name: Push Docker image to ECR Public
      run: |
        docker push public.ecr.aws/k5u0o7b3/team2-namegen:latest

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name <your-cluster-name> --region us-east-2

    - name: Deploy to EKS
      run: kubectl apply -f k8s-manifests/
